# Site settings
title: "KKu Island"
description: > 
  KKu Island Blog

author: KKu InSoo
email: kkuinsoo@gmail.com
twitter_username: 
github_username: kuinsoo

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "kuinsoo.github.io" # the base hostname & protocol for your site

google_analytics_id: 
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

